export const validExploreValues = [
  "pc_web_explorePage_all",
  "pc_web_explorePage_topics_singing_dancing",
  "pc_web_explorePage_topics_comedy",
  "pc_web_explorePage_topics_sports",
  "pc_web_explorePage_topics_anime_comics",
  "pc_web_explorePage_topics_relationship",
  "pc_web_explorePage_topics_shows",
  "pc_web_explorePage_topics_lipsync",
  "pc_web_explorePage_topics_daily_life",
  "pc_web_explorePage_topics_beauty_care",
  "pc_web_explorePage_topics_games",
  "pc_web_explorePage_topics_society",
  "pc_web_explorePage_topics_outfit",
  "pc_web_explorePage_topics_cars",
  "pc_web_explorePage_topics_food",
  "pc_web_explorePage_topics_animals",
  "pc_web_explorePage_topics_family",
  "pc_web_explorePage_topics_drama",
  "pc_web_explorePage_topics_fitness_health",
  "pc_web_explorePage_topics_education",
  "pc_web_explorePage_topics_technology",
];

export const exploreValueLabels: Record<string, string> = {
  "pc_web_explorePage_all": "All Topics",
  "pc_web_explorePage_topics_singing_dancing": "Singing & Dancing",
  "pc_web_explorePage_topics_comedy": "Comedy",
  "pc_web_explorePage_topics_sports": "Sports",
  "pc_web_explorePage_topics_anime_comics": "Anime & Comics",
  "pc_web_explorePage_topics_relationship": "Relationship",
  "pc_web_explorePage_topics_shows": "Shows",
  "pc_web_explorePage_topics_lipsync": "Lip Sync",
  "pc_web_explorePage_topics_daily_life": "Daily Life",
  "pc_web_explorePage_topics_beauty_care": "Beauty & Care",
  "pc_web_explorePage_topics_games": "Games",
  "pc_web_explorePage_topics_society": "Society",
  "pc_web_explorePage_topics_outfit": "Outfit",
  "pc_web_explorePage_topics_cars": "Cars",
  "pc_web_explorePage_topics_food": "Food",
  "pc_web_explorePage_topics_animals": "Animals",
  "pc_web_explorePage_topics_family": "Family",
  "pc_web_explorePage_topics_drama": "Drama",
  "pc_web_explorePage_topics_fitness_health": "Fitness & Health",
  "pc_web_explorePage_topics_education": "Education",
  "pc_web_explorePage_topics_technology": "Technology",
};